language: python

env:
  - TOXENV=py27
  - TOXENV=py27-simplejson
  - TOXENV=py34
  - TOXENV=docs

install: pip install tox coveralls

script: tox

after_success:
  - tox -e cover
  - coveralls

sudo: false
